ForumProject/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Entities;
using ForumProject.ViewModels.Role;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ForumProject.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole<int>> _roleManager;
        private readonly UserManager<User> _userManager;

        public RoleController(RoleManager<IdentityRole<int>> roleManager,
            UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles="admin")]
        [HttpGet]
        [Route("/role/create")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [Route("/role/create")]
        public async Task<IActionResult> Create(RoleCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole<int>
                {
                    Name = viewModel.RoleName
                };

                var result = await _roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Admin");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(" ", error.Description);
                }
            }

            return View(viewModel);
        }

        public IActionResult Delete()
        {
            return View();
        }

        [Authorize(Roles="admin")]
        [Route("/role/edit/{id}")]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var role = await _roleManager.FindByIdAsync(id.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = "Role cannot be found";
                return View("NotFound");
            }

            var viewModel = new RoleEditViewModel
            {
                Id = role.Id,
                Name = role.Name
            };

            foreach (var user in _userManager.Users.ToList())
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    viewModel.Users.Add(user.UserName);
                }
            }

            return View(viewModel);
        }

        [Authorize(Roles="admin")]
        [Route("/role/edit/{id}")]
        [HttpPost]
        public async Task<IActionResult> Edit(RoleEditViewModel viewModel)
        {
            var role = await _roleManager.FindByIdAsync(viewModel.Id.ToString());

            if (role == null)
            {
                ViewBag.ErrorMesage = "Role cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = viewModel.Name;
                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Admin");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(" ", error.Description);
                }
            }

            return View(viewModel);
        }
    }
}

ForumProject/Views/Admin/EditUsersInRole.cshtml
@using ForumProject.ViewModels
@model List<UserRoleViewModel>

@{
    var roleId = ViewBag.roleId;
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Add or remove users from the role</h2>
        </div>

        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr class="table-primary">
                        <th scope="col"></th>
                        <th scope="col">Number of Posts</th>
                        <th scope="col">Number of Comments</th>
                    </tr>
                </thead>
                @for (int i = 0; i < Model.Count; i++)
                {
                    <tbody>
                        <tr>
                            <td>
                                <input type="hidden" asp-for="@Model[i].Id"/>
                                <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                                <label class="form-check-label">
                                    @Model[i].UserName
                                </label>
                            </td>
                            <td>@Model[i].PostsCount</td>
                            <td>@Model[i].CommentsCount</td>
                        </tr>
                    </tbody>
                }
            </table>
            </div>

        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-outline-success" style="width:auto;"/>
            <a asp-controller="Role" asp-action="Edit" asp-route-id="@roleId" class="btn btn-outline-danger">
                Cancel
            </a>
        </div>
    </div>
</form>

ForumProject/Views/Admin/Index.cshtml
@model ForumProject.ViewModels.Admin.AdminIndexViewModel

<h2>All Roles</h2>

@if (Model.Roles.Any())
{
    <a class="btn btn-outline-success mb-3" style="width:auto;" asp-controller="Role" asp-action="Create">
        Create Role
    </a>

    foreach (var role in Model.Roles)
    {
        <div class="card mb-3">
            <div class="card-header">
                @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
                <div class="card-footer">
                    <a href="#" class="btn btn-outline-primary">Delete</a>
                    <a class="btn btn-outline-danger" asp-controller="Role" asp-action="Edit" asp-route-id="@role.Id">
                        Edit
                    </a>
                </div>
            </div>
        </div>
    }
}
else
{
    <h2>No roles yet!</h2>
}