ForumProject/ViewModels/Community/CommunityCreateVM.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ForumProject.ViewModels
{
    public class CommunityCreateVM
    {
        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [Required]
        [StringLength(100)]
        public string Description { get; set; }

        public IFormFile Photo { get; set; }

        [Required]      
        public int CategoryId { get; set; }
    }
}

ForumProject/ViewModels/Community/CommunityDetailsVM.cs
using System.Collections.Generic;
using ForumProject.ViewModels.Post;

namespace ForumProject.ViewModels.Community
{
    public class CommunityDetailsVM
    {
        public CommunityVM Community { get; set; }
        public IEnumerable<PostVM> Posts { get; set; }
    }
}

ForumProject/ViewModels/Community/CommunityIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForumProject.ViewModels
{
    public class CommunityIndexViewModel
    {
        public IEnumerable<CategoryVM> Categories { get; set; }
        public IEnumerable<CommunityVM> Communities { get; set; }
    }
}

ForumProject/ViewModels/Community/CommunityVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForumProject.ViewModels
{
    public class CommunityVM
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PhotoPath { get; set; }
        public int CategoryId { get; set; }
    }
}

ForumProject/Controllers/CommunityController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Linq;
using ForumProject.ViewModels.Post;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using DAL.Entities;
using System;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using ForumProject.ViewModels;
using ForumProject.ViewModels.Community;
using DAL.Interfaces;
using AutoMapper;
using DAL.DTOs.Community;
using DAL.DTOs.User;
using ForumProject.Utils;

namespace ForumProject.Controllers
{
    public class CommunityController : Controller
    {
        private readonly IWebHostEnvironment _appEnvironment;

        private readonly ICommunityRepository _communityRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPostRepository _postRepository;
        private readonly IMapper _mapper;

        private readonly UserManager<User> _userManager;

        public CommunityController(
            ICategoryRepository categoryRepository,
            UserManager<User> userManager,
            IWebHostEnvironment appEnvironment, 
            IPostRepository postRepository,
            IMapper mapper,
            ICommunityRepository communityRepository)
        {
            _categoryRepository = categoryRepository;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
            _postRepository = postRepository;
            _mapper = mapper;
            _communityRepository = communityRepository;
            _postRepository = postRepository;
        }

        [HttpGet]
        [Route("/communities/{categoryId?}")]
        public IActionResult Index(int? categoryId)
        {
            var categories = _categoryRepository.GetAll()
                .Select(category => _mapper.Map<CategoryVM>(category))
                .ToList();

            var communities = _communityRepository.GetAll()
                .Select(community => _mapper.Map<CommunityVM>(community));

            categories.Insert(0, new CategoryVM { Id = 0, Name = "All" });

            var viewModel = new CommunityIndexViewModel { Categories = categories, Communities = communities };

            if (categoryId != null && categoryId > 0)
            {
                viewModel.Communities = communities.Where(c => c.CategoryId == categoryId);
            }

            return View(viewModel);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        [Route("/community/create")]
        public IActionResult Create()
        {
            var categories = _categoryRepository.GetAll()
                .Select(category => _mapper.Map<CategoryVM>(category));

            ViewData["Categories"] = new SelectList(categories, "Id", "Name");

            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [Route("/community/create")]
        public async Task<IActionResult> Create(CommunityCreateVM viewModel)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);               
                var user = await _userManager.FindByIdAsync(userId);

                var community = _mapper.Map<CommunityDTO>(viewModel);
                community.Creator = _mapper.Map<UserDTO>(user);
                community.PhotoPath = ImageUtil.Upload(_appEnvironment, viewModel.Photo, "communities");

                _communityRepository.Add(community);
                return RedirectToAction("Details", "Community", new { id = community.Id });
            }

            return View(viewModel);
        }

        [HttpGet]
        [Route("/community/{id}", Name = "CommunityDetails")]
        public IActionResult Details(int id)
        {
            var community = _communityRepository.GetById(id);
            var communityVM = _mapper.Map<CommunityVM>(community);

            var posts = _postRepository.GetPostsByCommunity(community.Id)
                .Select(post => _mapper.Map<PostVM>(post))
                .ToList();

            posts.ForEach(post => post.Community = communityVM);
                              
            return View(new CommunityDetailsVM { Community = communityVM, Posts = posts});
        }
    }
}

ForumProject/Controllers/SurveyController.cs
using BLL.Interfaces;
using DAL.DTOs.Survey;
using DAL.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ForumProject.Controllers
{
    public class SurveyController : BaseController
    {
        private readonly ISurveyService _surveyService;

        public SurveyController(UserManager<User> userManager, ISurveyService surveyService):base(userManager)
        {
            _surveyService = surveyService;
        }

        public new IActionResult Index()
        {
            return View();
        }

        [Route("survey/create/{communityId}")]
        public IActionResult Create(int communityId)
        {
            var currentUserId = GetCurrentUserId();
            ViewData["CommunityId"] = communityId;
            ViewData["AuthorId"] = currentUserId;
            return View();
        }

        [HttpPost]
        [Route("survey/create/{communityId}")]
        public IActionResult Create(SurveyCreateDTO surveyCreateDTO)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _surveyService.CreateSurvey(surveyCreateDTO);
            return CreatedAtRoute("CommunityDetails", new { id = surveyCreateDTO.CommunityId }, null);
        }

        [Route("survey/details/{surveyId}")]
        public IActionResult Details(int surveyId)
        {
            var currentUserId = GetCurrentUserId();
            var surveyWithResultsDto = _surveyService.GetSurveyWithResults(surveyId, currentUserId);
            return View(surveyWithResultsDto);
        }

        [HttpPost]
        public IActionResult Update(SurveyFillOutFormDTO form)
        {
            form.UserId = (int)GetCurrentUserId();
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _surveyService.FillOutSurvey(form);
            return Ok();
        }

        [Route("survey/results/{surveyId}")]
        public IActionResult Results(int surveyId)
        {
            var currentUserId = GetCurrentUserId();
            var surveyWithResultsDto = _surveyService.GetSurveyWithResults(surveyId, currentUserId);
            return PartialView("_SurveyResultsPartial", surveyWithResultsDto);
        }
    }
}

ForumProject/Views/Community/Create.cshtml
@model ForumProject.ViewModels.CreateCommunityViewModel

<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <h4>Create community</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo"></label>
                <div class="custom-file">
                    <input asp-for="Photo" class="form-control custom-file-input"/>
                    <label class="custom-file-label">Choose File...</label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category</label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories">
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-outline-success">Create</button>
        </form>
    </div>
</div>

ForumProject/Views/Community/Details.cshtml
@model ForumProject.ViewModels.Community.CommunityDetailsViewModel

<div class="about-community">
    <span class="about">About community</span>
    <span class="community-title">@Model.Community.Title</span>
    <span>@Model.Community.Description</span>
</div>

@if (User.Identity.IsAuthenticated)
{
    <a asp-controller="Post" asp-action="Create" asp-route-communityId="@Model.Community.Id" class="btn btn-info">
        CREATE POST
    </a>
    <a class="create-survey" asp-controller="Survey" asp-action="Create" asp-route-communityId="@Model.Community.Id">
        CREATE POST WITH SURVEY
    </a>
}
else
{
    <p style="color: red;">You have to login to create post on community!</p>
}

<div class="post-list">
    @if (@Model.Posts.Any())
    {
        @foreach (var post in Model.Posts)
        {
            @if(post.SurveyId == null)
            {
                <a class="post-item" target="_blank" asp-controller="Post" asp-action="Details" asp-route-id="@post.Id">
                    <span class="title">@post.Title</span>
                    <span>Posted by @post.AuthorName</span>
                    <span>@post.CommentsCount Comments</span>
                </a>
            }
            else
            {
                <a class="post-item" target="_blank" asp-controller="Survey" asp-action="Details" asp-route-surveyId="@post.SurveyId">
                    <span class="title">@post.Title</span>
                    <span>Posted by @post.AuthorName</span>
                    <span>@post.CommentsCount Comments</span>
                </a>
            }
        }
    }
    else
    {
    <h3>There are no posts yet!</h3>
    }
</div>

ForumProject/Views/Community/Index.cshtml
@model ForumProject.ViewModels.CommunityIndexViewModel

<div class="list-group float-left" style="width: 200px; margin-top: 20px;">
    @foreach (var category in Model.Categories)
    {
        <a asp-controller="Community" asp-action="Index" asp-route-categoryId="@category.Id" class="list-group-item list-group-item-action">
            @category.Name
        </a>
    }
</div>

<div class="list-group" align ="center" style="width:300px; margin-top: 30px; margin-right: 40px;">
    @foreach (var community in Model.Communities)
    {
        <a class="list-group-item list-group-item-action" asp-controller="Community" asp-action="Details" asp-route-id="@community.Id">
            <span>
                <img src="@Url.Content("~/images/communities/")/@community.PhotoPath" class="rounded float-left" width="60" height="60" asp-append-version="true"/>
            </span>
            <h5>@community.Title</h5>
        </a>
    }
</div>